name: play_tv
description: Flutter App


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.7.9"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  provider: ^6.0.3
  connectivity: ^3.0.6
  dio: ^4.0.6
  http: ^0.13.4
  shared_preferences: ^2.2.0
  flutter_html: ^3.0.0-alpha.5
  package_info: ^2.0.2
  flutter_local_notifications: ^9.7.0
  flutter_svg: ^1.1.1+1
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  youtube_player_iframe: ^4.0.4
  webview_flutter: ^4.2.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  google_sign_in: ^6.1.4
  video_player: ^2.7.0
  wakelock: ^0.6.2
  chewie: ^1.5.0
  auto_orientation: ^2.3.1
  flutter_share: ^2.0.0
  device_information: ^0.0.4
  flutter_focus_watcher:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/images/channel_images/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
